"""Jadikan email Pengguna opsional

Revision ID: 6295c77e5da3
Revises: ddfb8ca3f273
Create Date: 2025-11-17 06:05:15.482871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6295c77e5da3'
down_revision = 'ddfb8ca3f273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pengguna', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pengguna', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
