"""nambah absen

Revision ID: 9312315e3849
Revises: dc6f31b7c696
Create Date: 2025-11-20 20:59:58.470263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9312315e3849'
down_revision = 'dc6f31b7c696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Profil', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nomor_absen', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Profil', schema=None) as batch_op:
        batch_op.drop_column('nomor_absen')

    # ### end Alembic commands ###
