"""ganti nama depan nama belakagn jadi nama lengkap

Revision ID: dc6f31b7c696
Revises: def4b009ca00
Create Date: 2025-11-20 15:58:17.653537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc6f31b7c696'
down_revision = 'def4b009ca00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Profil', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_lengkap', sa.String(length=100), nullable=True))
        batch_op.drop_column('nama_belakang')
        batch_op.drop_column('nama_depan')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Profil', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_depan', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nama_belakang', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('nama_lengkap')

    # ### end Alembic commands ###
