"""hapus database laporan

Revision ID: def4b009ca00
Revises: 1fa442d7bc76
Create Date: 2025-11-18 14:38:06.979868

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'def4b009ca00'
down_revision = '1fa442d7bc76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Laporan', schema=None) as batch_op:
        batch_op.drop_column('waktu_tanggal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Laporan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waktu_tanggal', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
